In [ ]:
import matplotlib.pyplot as plt
from matplotlib import gridspec
import seaborn as sns
import pandas as pd
from tqdm.notebook import tqdm

from scipy.special import softmax
from scipy.spatial.distance import cdist
import numpy as np
import torch

from sklearn.datasets import make_classification, load_iris, load_wine
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold, ParameterGrid
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing

from mlxtend.plotting import plot_decision_regions

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd /content/drive/MyDrive/Colab Notebooks/

/content/drive/MyDrive/Colab Notebooks

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [71]:
data = pd.read_csv('dataset.csv', sep=',')
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.str0)
#def convert(data):
#    number = preprocessing.LabelEncoder()
#    data['Name'] = number.fit_transform(data['Name'])
#    data=data.fillna(-999) # fill holes with default value
#    return data

#data = convert(data)
data = clean_dataset(data)
X = data[['Age', 'Sleep', 'Headache', 'Diarea', 'Stomachache', 'Bodeache', 'Difcolor', 'Cough', 'Sorethroat', 'Fatigue']]
#X = clean_dataset(X)
Y = data['Name']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y,  
                                                    test_size=0.2, 
                                                    random_state=0)

#from sklearn.model_selection import train_test_split
#train, test = train_test_split(data, test_size = 0.2)
#train_features = train[['Age', 'Sleep', 'Headache', 'Diarea', 'Stomachache', 'Bodeache', 'Difcolor', 'Cough', 'Sorethroat', 'Fatigue']]

In [68]:
data

,Name,Age,Sleep,Headache,Diarea,Stomachache,Bodeache,Difcolor,Cough,Temper,Sorethroat,Fatigue,Runnynose,Chestpain,Reducedappetite,Emetic,Sneezing,Wheeze
0,1,25,0,0,0,0,0,0,1,2,1,0,0,0,1,0,0,0
1,2,62,0,0,0,0,1,0,1,2,1,0,0,0,0,1,0,0
2,3,30,0,0,0,0,1,0,1,2,0,0,0,0,1,0,0,0
3,4,19,0,0,0,0,0,0,1,2,0,0,0,0,0,1,0,0
4,5,28,1,1,0,1,1,1,1,1,0,0,1,1,1,0,0,1
5,6,40,1,1,0,0,1,0,1,2,0,1,0,0,1,0,0,1
6,7,62,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0
7,8,23,1,1,0,0,1,1,1,0,0,0,0,0,0,1,0,0
8,9,34,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,1
9,10,39,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,1
10,11,46,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
11,12,20,0,1,1,0,1,1,1,0,0,0,0,0,0,1,0,0
12,13,27,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1
13,14,19,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1
14,15,28,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
15,16,40,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

## Метод k-ближайших соседей

In [76]:
print('K\t', 'Обучение\t', 'Контроль');

models = []
for n_neighbors in range(1, 12):
    model = KNeighborsClassifier(n_neighbors=n_neighbors)
    model.fit(X_train, Y_train)
    models.append(model)
    print(n_neighbors, '\t', model.score(X_train, Y_train), end='')
    a = str(model.score(X_train, Y_train))
    if len(a) < 6:
        print('\t', end='')
    print('\t', model.score(X_test, Y_test))

K	 Обучение	 Контроль
1 	 1.0		 0.0
2 	 0.5		 0.0
3 	 0.3333333333333333	 0.0
4 	 0.25		 0.0
5 	 0.16666666666666666	 0.0
6 	 0.16666666666666666	 0.0
7 	 0.16666666666666666	 0.0
8 	 0.08333333333333333	 0.0
9 	 0.08333333333333333	 0.0
10 	 0.08333333333333333	 0.0
11 	 0.08333333333333333	 0.0